/** @type {import('jest').Config} */
module.exports = {
  preset: 'jest-expo',
  testMatch: [
    '**/__tests__/**/*.test.[jt]s?(x)',
  ],
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    '!src/types/**',
    '!src/screens/**',
    '!src/components/**',
    '!src/context/**',
    '!src/hooks/**',
    '!src/index.ts',
    '!src/api/auth.api.ts',
    '!src/api/customers.api.ts',
    '!src/api/locations.api.ts',
    '!src/api/machinery.api.ts',
    '!src/api/machineryAlerts.api.ts',
    '!src/api/maintenance.api.ts',
    '!src/api/production.api.ts',
    '!src/api/products.api.ts',
    '!src/api/sales.api.ts',
    '!src/api/users.api.ts',
    '!src/api/client.ts',
    '!src/utils/notifications.ts',
    '!src/utils/storage.ts',
    '!src/utils/jwt.ts',
    '!src/constants/colors.ts',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'text-summary', 'lcov', 'html'],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  setupFiles: ['<rootDir>/__tests__/mocks.ts'],
  setupFilesAfterEnv: ['<rootDir>/__tests__/setup.ts'],
  transformIgnorePatterns: [
    'node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@sentry/react-native|native-base|react-native-svg)',
  ],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
  },
};
